<li class="span3">
                <div class="thumbnail">
<a href="//liivro.com/book/show/<?php echo $book['id']; ?>"><img data-src="holder.js/300x200" alt="300x200"  src="<?php echo $book['picture']; ?>" /></a>

               <div class="caption">
                    <h6><a href="//liivro.com/book/show/<?php echo $book['id']; ?>"><?php echo $book['title']; ?></a></h6>
                    <p>R$ <?php echo $book['price']; ?></p>
                  </div>
                </div>
              </li>