 <script src="//liivro.com/js/jquery.js"></script>
 <script src="//liivro.com/js/bootstrap.js"></script>
 <script src="//liivro.com/js/jquery.jkit.1.1.10.js"></script>
 <script src="//liivro.com/js/jquery.easing.1.3.js"></script>


<script type="text/javascript">
    $("[data-rel=tooltip]").tooltip();
</script>

<script type="text/javascript">
$(document).ready(function(){
  $('body').jKit();
});
</script>


  </body>
</html>
