<footer class="footer">
<div class="container">
<div class="row-fluid">
  <div class="span6"> <p class="copyright"><img class="foot-logo" src="images/logo-ts.png" alt="Brand Logo"/> &copy; 2013 <strong>Liivro.com</strong> </p></div>
<div class="span6">   <div class="pagination pull-right">
 <ul>
<li><a data-rel="tooltip" data-placement="top" data-original-title="Follow us on Twitter" href="#"><i class="icon-twitter"></i></a></li>
<li><a data-rel="tooltip" data-placement="top" data-original-title="Share us on Pinterest" href="#"><i class="icon-pinterest"></i></a></li>
<li><a data-rel="tooltip" data-placement="top" data-original-title="Like us on Facebook" href="#"><i class="icon-facebook"></i></a></li>
<li><a data-rel="tooltip" data-placement="top" data-original-title="+1 us on Google+" href="#"><i class="icon-google-plus"></i></a></li>          
</ul>
</div>
</div>
</div>
</div>
</footer>