<div id="header">
    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
         <a href="index.htm"> <h1>.</h1></a>
          <div class="nav-collapse collapse">
            <form class="navbar-form pull-left">
<div class="input-append">
  <input class="span3" id="appendedInputButtons" type="text">
  <button class="btn btn-primary" type="button"><i class="icon-search"></i></button>
</div>           
</form>
            <ul class="nav">
              <li class="active"><a href="#">Cadastrar Livro</a></li>
              <li><a href="#">Meus Livros</a></li>
              <li><a href="#">Matemática</a></li>
              <li><a href="#">Computação</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="404.htm">404 Page</a></li>
                  <li><a href="page-elements.htm">Page elements</a></li>
                  <li><a href="login.htm">Login Page</a></li>
                  <li><a href="register.htm">Register Page</a></li>
                  <li><a href="pricing-plans.htm">Pricing Plans</a></li>
                </ul>
              </li>
            </ul>
         <p class="navbar-text pull-right">
            <a href="//liivro.com/index/logout" class="navbar-link">sair</a>
            </p> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
 </div>