<div id="header">
    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
         <a href="//liivro.com"></a>
          <div class="nav-collapse collapse">
            <form class="navbar-form pull-left" method="POST" action="//liivro.com/book/search">
<div class="input-append">
  <input class="span3" id="appendedInputButtons" type="text" name="term">
  <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
</div>           
</form>
            <ul class="nav">
              <li class="active"><a href="//liivro.com/book/create">Cadastrar Livro</a></li>
              <li><a href="//liivro.com/user/books">Meus Livros</a></li>
              <li><a href="//liivro.com/listing/index/1">Matemática</a></li>
              <li><a href="//liivro.com/listing/index/6">Computação</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="//liivro.com/listing/index">Todas</a></li>
                  <li><a href="//liivro.com/listing/index/1">Matemática</a></li> 
                  <li><a href="//liivro.com/listing/index/2">Física</a></li> 
                  <li><a href="//liivro.com/listing/index/3">Biologia</a></li> 
                  <li><a href="//liivro.com/listing/index/4">Geografia</a></li> 
                  <li><a href="//liivro.com/listing/index/5">Estatística</a></li> 
                  <li><a href="//liivro.com/listing/index/6">Computação</a></li> 
                  <li><a href="//liivro.com/listing/index/7">Administração</a></li> 
                  <li><a href="//liivro.com/listing/index/8">Economia</a></li> 
                  <li><a href="//liivro.com/listing/index/9">História</a></li> 
                  <li><a href="//liivro.com/listing/index/10">Química</a></li> 
                  <li><a href="//liivro.com/listing/index/11">Design</a></li> 
                  <li><a href="//liivro.com/listing/index/12">Artes</a></li> 
                  <li><a href="//liivro.com/listing/index/13">Outros</a></li>
                </ul>
              </li>
            </ul>
         <p class="navbar-text pull-right">
            <a href="//liivro.com/index/logout" class="navbar-link">sair</a>
            </p> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
 </div>