<?php if ($total_count > $perPage): ?>
<div class="pagination pagination-small pull-right">
    <ul>
    	<li><a href="#">«</a></li>
    	<?php
    	$page = 1;
    	while ($total_count >= $perPage): ?>
        <li><a href="//liivro.com/listing/index/<?php echo $category . '/' . $page; ?>"><?php echo $page; ?></a></li>
    	<?php
    	   $page++;
    	   $total_count -= $perPage;
    	endwhile; ?>
        <li><a href="#">»</a></li>
    </ul>
</div>
<?php endif; ?>