<div id="info-unit"> <div class="alert alert-block alert-info fade in">
<button type="button" class="close" data-dismiss="alert">×</button>
<h4 class="alert-heading">Atenção! Você ainda não confirmou sua universidade.</h4>
<p>Para utilizar o Liivro.com da forma correta, é necessário que cadastre seu e-mail da universidade no sistema.<br />
Você tem <strong>7 dias</strong> para navegar pelo site apenas com a conta do Facebook.
<br />Depois deste período, só será possível ver o conteúdo
<strong>depois de ativar a conta</strong>.
</p>
<p><a class="btn btn-primary" href="//liivro.com/university/register">Ativar Universidade</a></p>
</div>
</div>