<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

<?php $this->partial('shared/listing/trial'); ?>

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->

<div class="options-bar"><select class="span2 pull-left"><option>Ordenar </option>
  <option>Data</option>
  <option>Popular</option>
  <option>Maior avaliação</option>
  <option>Menor avaliação</option>
</select><span><strong>12.487</strong> títulos achados</span>
</div>

 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">
<ul class="thumbnails">
<?php 
for ($i = 0; $i < 32; $i++) $this->partial('shared/listing/book'); ?>
</ul>
</div>

<?php $this->partial('shared/listing/pagination'); ?>


</div>

 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">categorias</li>
      <li class="active"><a href="#"> Todas</a></li>
      <li><a href="#"> Matemática</a></li>
      <li><a href="#"> Física</a></li>
      <li><a href="#"> Computação</a></li>
      <li><a href="#"> Química</a></li>
      <li><a href="#"> Biologia</a></li>
    </ul><br />
    <ul class="nav nav-list">
      <li class="nav-header">filtrar por</li>
      <li class="active"><a href="#"><i class="icon-time"></i> Mais Recente</a></li>
      <li><a href="#"><i class="icon-star-empty"></i> Mais Barato</a></li>
    </ul><br />
 <ul class="nav nav-list">
      <li class="nav-header">Administração</li>
      <li class="active"><a href="#"> Cadastrar Livro</a></li>
      <li><a href="#"> Meus Livros</a></li>
    </ul>
    <br />
    
    

<div class="module-top"><i class="icon-lock"></i> Registrar Universidade</div>
<div class="module">
<form method="post" action="?" data-jkit="[form:validateonly=true]">
  <fieldset>
    <label class="label-main">e-mail</label>
    <input name="miniusername" class="span10" id="miniusername"  type="text" data-jkit="[validate:required=true;min=3;max=10;error=Please enter your username (3-10 characters)]">
    <button name="send" type="submit" value="Submit"  class="btn btn-small">Enviar</button>
  </fieldset>
</form></div>

</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>