<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

<!--<?php $this->partial('shared/listing/trial'); ?>-->

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->
 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">
	<h3>Seu e-mail foi enviado. Aguarde a chegada dele para ativar sua conta.</h3>
</div>


</div>

 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
   <br />
   
    <br />
    
    



</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>