<form action="http://liivro.com/book/doCreate" method="POST" enctype="multipart/form-data">
	Title: <input type="text" name="title" id="title" /><br />
	Price: <input type="text" name="price" id="price" /><br />
	Category: <input type="text" name="category" id="category" /><br />
	Picture: <input type="file" name="picture" id="picture" /><br />
	<input type="submit" value="Enviar" /><br />
</form>