<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

<!--<?php $this->partial('shared/listing/trial'); ?>-->

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->

<div class="options-bar"><h1><?php if ($success) {
										echo "Livro cadastrado com sucesso! <a href='//liivro.com/book/show/", $book_id, "'>Veja seu anúncio!</a>";
									} else {
										echo "Desculpe :( <br />Falha ao cadastrar livro.";
									}
							?></h1>
</div>

 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">


</div>


</div>

 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
   <br />
   
    <br />
    
    



</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>