<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

<?php
if (!$confirmed_user) {
  $this->partial('shared/listing/trial');
}
?>

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->


 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">
<ul class="thumbnails">
<?php
foreach ($result as $book) {
  $this->partial('shared/listing/book', array('book' => $book));
}
?>
</ul>
</div>

<?php $this->partial('shared/listing/pagination'); ?>


</div>

 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">categorias</li>
      <li class="active"><a href="//liivro.com/listing/index"> Todas</a></li>
      <li><a href="//liivro.com/listing/index/1"> Matemática</a></li>
      
      <li><a href="//liivro.com/listing/index/2"> Física</a></li>
      
      <li><a href="//liivro.com/listing/index/3"> Biologia</a></li>
      
      <li><a href="//liivro.com/listing/index/4"> Geografia</a></li>
      
          <li><a href="//liivro.com/listing/index/5"> Estatística</a></li>
      
          <li><a href="//liivro.com/listing/index/6"> Computação</a></li>
      
          <li><a href="//liivro.com/listing/index/7"> Administração</a></li>
      
          <li><a href="//liivro.com/listing/index/8"> Economia</a></li>
      
          <li><a href="//liivro.com/listing/index/9"> História</a></li>
      
          <li><a href="//liivro.com/listing/index/10"> Química</a></li>
      
          <li><a href="//liivro.com/listing/index/11"> Design</a></li>
      
          <li><a href="//liivro.com/listing/index/12"> Artes</a></li>
      
          <li><a href="//liivro.com/listing/index/13"> Outros</a></li>
      
    </ul><br />
    <ul class="nav nav-list">
      <li class="nav-header">filtrar por</li>
      <li class="active"><a href="#"><i class="icon-time"></i> Mais Recente</a></li>
      <li><a href="#"><i class="icon-star-empty"></i> Mais Barato</a></li>
    </ul><br />
 <ul class="nav nav-list">
      <li class="nav-header">Administração</li>
      <li class="active"><a href="//liivro.com/book/create"> Cadastrar Livro</a></li>
      <li><a href="//liivro.com/user/books"> Meus Livros</a></li>
    </ul>
    <br />
    
    
<?php if (!$confirmed_user): ?>
<div class="module-top"><i class="icon-lock"></i> Registrar Universidade</div>
<div class="module">
<form action="http://liivro.com/university/doRegister" method="POST" data-jkit="[form:validateonly=true]">
  <fieldset>
    <label class="label-main">e-mail</label>
    <input name="user_email" class="span10" id="miniusername"  type="text" data-jkit="[validate:required=true;min=3;max=30;error=Entre seu e-mail de universidade]">
    <button name="send" type="submit" value="Submit"  class="btn btn-small">Cadastrar</button>
  </fieldset>
</form></div>
<?php endif; ?>

</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>