<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->

<?php if (isset($book) && $book != array() && $book != false): ?>


 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">
<center><img src="<?php echo $book['picture']; ?>" /><br />
<h4><?php echo $book['title']; ?></h4>
<h5>R$ <?php echo $book['price']; ?></h5></center>
</div>


</div>
 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
   <img src="//graph.facebook.com/<?php echo $user['uid']; ?>/picture" />&nbsp;&nbsp;<a href="//facebook.com/<?php echo $user['uid']; ?>"><?php echo $user['name']; ?></a><br /><br />
   <strong>Contato:</strong> <br />
   <?php echo $user['general_email']; ?><br />
   <?php echo $user['university_email']; ?><br />
    

<?php endif; ?>

</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>