<?php $this->partial('shared/listing/base'); ?>

<!-- Start Header -->

<?php $this->partial('shared/listing/header'); ?>

 <!-- End Header -->



<div class="container">

 <!-- Start Info Unit -->

<!--<?php $this->partial('shared/listing/trial'); ?>-->

 <!-- End Info Unit -->

<div>
 
<div class="row-fluid" >
<div class="span9 main-section">


 <!-- Options bar (Left Section) -->


<div class="options-bar"><h4>Meus livros</h4>
</div>

 <!-- End Options Bar -->


 <!-- Start Left Section -->

<div class="row-fluid">
<?php
if ($books == array() ||  $books == NULL) {
	echo "<h3>Você não tem livros cadastrados ainda.</h3>";
} else {
	echo "<table>";
	foreach ($books as $book) {
		echo "<tr><td><img src='", $book['picture'], "' style='max-height: 100px; max-width: 100px;'/></td><td><a href='//liivro.com/book/show/", $book['id'], "'>", $book['title'], "</a></td><td>
		<a href='//liivro.com/book/edit/", $book['id'], "'>Editar</a></td><td><a href='//liivro.com/book/delete/", $book['id'],"'>Excluir</a></td></tr>";
	}
	echo "</table>";
}
?>
</div>



</div>

 <!-- End Left Section -->

 <!-- Start Right Section -->
  <div id="side-section" class="span3">
   <br />
   
    <br />
    
    



</div>
<hr>
</div>
</div>
</div>

<?php $this->partial('shared/listing/footer'); ?>



    <!-- Include Javascript/JQuery Assets
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<?php $this->partial('shared/listing/bottom'); ?>